/*
 * Fluree HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package fluree

type Body1 struct {
	FlureeServerComponentsHttpquery  string `json:"fluree.server.components.http/query"`
	FlureeServerComponentsHttpformat string `json:"fluree.server.components.http/format"`
}
